// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIF2g9n6ZoK8rxFGObq4wfUl81Tbt7u8',
    appId: '1:566332137185:android:e9b76b291afb32e7d6e1a0',
    messagingSenderId: '566332137185',
    projectId: 'custard-kmp',
    databaseURL: 'https://custard-kmp-default-rtdb.firebaseio.com',
    storageBucket: 'custard-kmp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeTdRjDoxK981gszgVHpv57N-4K1iY3nA',
    appId: '1:566332137185:ios:1499cc84f77914e9d6e1a0',
    messagingSenderId: '566332137185',
    projectId: 'custard-kmp',
    databaseURL: 'https://custard-kmp-default-rtdb.firebaseio.com',
    storageBucket: 'custard-kmp.appspot.com',
    iosClientId: '566332137185-m3jigvcu1bpnopbem2dqa9l2arq4iufo.apps.googleusercontent.com',
    iosBundleId: 'app.custard.custardFlutter',
  );
}
